package agent

import "math/rand/v2"

var adverbs = []string{
	"absurdly", "awkwardly", "barely", "begrudgingly", "bizarrely",
	"blissfully", "boldly", "briskly", "casually", "cautiously",
	"chaotically", "cheerfully", "clumsily", "comically", "coolly",
	"curiously", "dangerously", "daringly", "defiantly", "delightfully",
	"desperately", "diabolically", "dramatically", "dreamily", "dryly",
	"eagerly", "effortlessly", "eloquently", "endlessly", "enthusiastically",
	"epically", "errantly", "eternally", "excessively", "exclusively",
	"fabulously", "faintly", "fearlessly", "ferociously", "fiercely",
	"flagrantly", "flawlessly", "foolishly", "frantically", "freely",
	"frequently", "furiously", "gallantly", "gently", "genuinely",
	"gleefully", "gloriously", "gracefully", "gravely", "grumpily",
	"hastily", "heroically", "hilariously", "humbly", "hungrily",
	"hypnotically", "impossibly", "impulsively", "incidentally", "incredibly",
	"infamously", "inexplicably", "intensely", "ironically", "jokingly",
	"joyfully", "justly", "keenly", "laughably", "lavishly",
	"lazily", "legendarily", "loftily", "ludicrously", "magnificently",
	"majestically", "merrily", "mightily", "mildly", "mischievously",
	"modestly", "monstrously", "mysteriously", "neatly", "nervously",
	"nobly", "noisily", "notably", "notoriously", "obscurely",
	"oddly", "outrageously", "passionately", "patiently", "peculiarly",
	"perfectly", "perpetually", "pleasantly", "pluckily", "politely",
	"practically", "precisely", "probably", "profoundly", "quietly",
	"quizzically", "radically", "recklessly", "reluctantly", "remarkably",
	"restlessly", "ridiculously", "rightly", "roughly", "royally",
	"ruthlessly", "sarcastically", "savagely", "secretly", "serenely",
	"shamelessly", "sharply", "shrewdly", "silently", "simply",
	"skeptically", "sleepily", "slightly", "slyly", "smugly",
	"sneakily", "solemnly", "somewhat", "spectacularly", "splendidly",
	"stealthily", "stoically", "strangely", "stubbornly", "stupendously",
	"subtly", "suddenly", "supposedly", "supremely", "suspiciously",
	"swiftly", "terribly", "theatrically", "thoroughly", "totally",
	"tremendously", "triumphantly", "truculently", "truly", "turbulently",
	"unabashedly", "undeniably", "unexpectedly", "unfairly", "universally",
	"unnervingly", "unusually", "utterly", "vaguely", "valiantly",
	"vastly", "vengefully", "vigorously", "virtually", "vividly",
	"voluntarily", "whimsically", "wickedly", "wildly", "wistfully",
	"wonderfully", "worryingly", "zealously",
}

var adjectives = []string{
	"abrupt", "adventurous", "ancient", "arcane", "audacious",
	"bashful", "bewildered", "blazing", "bold", "brainy",
	"brave", "breezy", "brilliant", "brisk", "brooding",
	"bubbly", "calm", "cautious", "chaotic", "cheerful",
	"chilly", "clever", "clumsy", "colossal", "cosmic",
	"cozy", "crafty", "cranky", "crispy", "curious",
	"dapper", "daring", "dazzling", "defiant", "determined",
	"devious", "dizzy", "dreamy", "dusty", "eager",
	"eccentric", "eerie", "electric", "elegant", "elusive",
	"enchanted", "enigmatic", "epic", "exotic", "explosive",
	"fabled", "fearless", "feisty", "feral", "fierce",
	"fiery", "flashy", "fluffy", "foolish", "frosty",
	"furious", "galactic", "gentle", "ghostly", "gigantic",
	"glacial", "gleaming", "gloomy", "golden", "graceful",
	"grizzled", "grumpy", "hasty", "hazy", "heroic",
	"hollow", "humble", "hungry", "icy", "impish",
	"infamous", "inventive", "invisible", "jolly", "jovial",
	"jubilant", "keen", "knotty", "lanky", "lazy",
	"legendary", "lively", "lone", "lucid", "luminous",
	"lurking", "majestic", "mellow", "menacing", "mighty",
	"misty", "moody", "mossy", "muffled", "mystic",
	"nebulous", "nimble", "noble", "nocturnal", "odd",
	"ominous", "optimistic", "ornery", "patient", "peculiar",
	"phantom", "plucky", "polar", "polished", "prickly",
	"primal", "proud", "puzzled", "quirky", "radiant",
	"rampant", "raucous", "reckless", "relentless", "resilient",
	"restless", "ridged", "rogue", "roving", "rugged",
	"rustic", "savage", "scrappy", "secretive", "serene",
	"shadowy", "shaky", "sharp", "shifty", "silent",
	"sleepy", "sly", "smoldering", "sneaky", "solemn",
	"spectral", "spicy", "stellar", "stiff", "stoic",
	"stormy", "stubborn", "subtle", "sunlit", "surly",
	"swift", "tangled", "tenacious", "thorny", "thundering",
	"timid", "towering", "turbulent", "twilight", "twisted",
	"uncanny", "unruly", "upbeat", "valiant", "vast",
	"vengeful", "vigilant", "volatile", "wandering", "wary",
	"whimsical", "wicked", "wild", "wily", "windswept",
	"wise", "witty", "wondrous", "wooly", "zany",
	"zealous", "zen",
}

var names = []string{
	"ada", "aegis", "aether", "apollo", "archer",
	"arrow", "ash", "atlas", "aurora", "avalon",
	"banshee", "basalt", "beacon", "birch", "blade",
	"blaze", "bolt", "briar", "byte", "cadence",
	"calyx", "carbon", "cascade", "cedar", "chimera",
	"cipher", "cirrus", "cleo", "cobalt", "comet",
	"coral", "cosmos", "coyote", "crane", "crimson",
	"crow", "cypher", "dagger", "dawn", "delta",
	"djinn", "drake", "drift", "dusk", "echo",
	"ember", "enigma", "falcon", "fang", "fern",
	"finch", "flare", "flint", "flux", "forge",
	"fox", "frost", "fury", "gale", "garnet",
	"ghost", "glacier", "glyph", "goblin", "granite",
	"griffin", "grim", "haze", "helix", "hex",
	"horizon", "hydra", "indigo", "ink", "ion",
	"iris", "iron", "ivy", "jade", "jasper",
	"jester", "jinx", "kai", "karma", "kestrel",
	"kite", "kraken", "lark", "lava", "lemon",
	"lichen", "lightning", "locus", "lotus", "luna",
	"lynx", "magpie", "mantis", "maple", "marble",
	"mars", "merlin", "meteor", "mica", "mirage",
	"mist", "mongoose", "moss", "moth", "nebula",
	"neon", "nexus", "nimbus", "nova", "nucleus",
	"nyx", "oak", "obsidian", "onyx", "opal",
	"orbit", "orca", "osprey", "otter", "oxide",
	"panther", "paradox", "pebble", "pepper", "phantom",
	"phoenix", "pine", "pixel", "plume", "prism",
	"pulse", "pyre", "quartz", "quest", "raven",
	"reef", "ripple", "rogue", "rover", "rune",
	"rust", "sable", "sage", "scorch", "scout",
	"sequoia", "shade", "shard", "sigil", "silk",
	"silver", "slate", "smog", "solar", "spark",
	"sphinx", "spruce", "static", "steel", "storm",
	"strider", "summit", "surge", "swift", "talon",
	"tarn", "tempest", "thistle", "thorn", "thunder",
	"tide", "titan", "torrent", "totem", "tundra",
	"vapor", "vector", "venom", "vertex", "vesper",
	"viper", "void", "volt", "vortex", "vulcan",
	"warden", "wave", "whisper", "willow", "wisp",
	"wolf", "wren", "zenith", "zephyr", "zero",
}

// GenerateName returns a random human-friendly name in "adverb-adjective-name" format.
func GenerateName() string {
	a := adverbs[rand.IntN(len(adverbs))]
	b := adjectives[rand.IntN(len(adjectives))]
	c := names[rand.IntN(len(names))]
	return a + "-" + b + "-" + c
}
