export const queryKeys = {
  agents: (active?: boolean) => active === false ? ["agents", "all"] as const : ["agents", "active"] as const,
  agentsPaginated: (active?: boolean) => active === false ? ["agents", "all", "paginated"] as const : ["agents", "active", "paginated"] as const,
  agent: (id: string) => ["agents", id] as const,
  board: (project: string) => ["board", project] as const,
  config: ["config"] as const,
  projects: ["projects"] as const,
  quota: ["quota"] as const,
  skills: ["skills"] as const,
  traces: ["traces"] as const,
  tracesPaginated: ["traces", "paginated"] as const,
  trace: (id: string) => ["traces", id] as const,
  tracks: (project?: string) => ["tracks", project] as const,
  tracksPaginated: (project?: string) => ["tracks", project, "paginated"] as const,
  syncStatus: (slug: string) => ["syncStatus", slug] as const,
  status: ["status"] as const,
  sshKeys: ["sshKeys"] as const,
  tour: ["tour"] as const,
  tourDemoBoard: ["tour", "demo-board"] as const,
  setupStatus: (slug: string) => ["setupStatus", slug] as const,
  preflight: ["preflight"] as const,
  trackDetail: (trackId: string, project: string) => ["tracks", trackId, project] as const,
  projectDiff: (slug: string, branch: string) => ["projectDiff", slug, branch] as const,
  projectBranches: (slug: string) => ["projectBranches", slug] as const,
  projectMetadata: (slug: string) => ["projectMetadata", slug] as const,
  projectSettings: (slug: string) => ["projectSettings", slug] as const,
  queue: (projectSlug?: string) => projectSlug ? ["queue", projectSlug] as const : ["queue"] as const,
  swarm: (projectSlug?: string) => projectSlug ? ["swarm", projectSlug] as const : ["swarm"] as const,
  reliabilityEvents: (filters?: Record<string, string>) => ["reliability", "events", filters] as const,
  reliabilityEventsPaginated: (filters?: Record<string, string>) => ["reliability", "events", filters, "paginated"] as const,
  reliabilitySummary: (since?: string, bucket?: string) => ["reliability", "summary", since, bucket] as const,
};
